version: 2
jobs:
  build:
    machine: true
    working_directory: ~/google-common-protos-scala
    steps:
      - checkout
      - restore_cache:
          keys:
            - ivy
      - run: sbt ";set Global / patchVersion := Some(\"$CIRCLE_BUILD_NUM\");publish"
      - save_cache:
          key: ivy
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: release
