version: 2
jobs:
  build:
    docker:
      - image: mtranter/sbt-protoc:1.2.8_2.12
    working_directory: ~/google-common-protos-scala
    steps:
      - checkout
      - restore_cache:
          keys:
            - ivy
      - run: git submodule sync
      - run: git submodule update --init
      - run: apt-get update && apt-get install libatomic1
      - run: sbt ";set Global / patchVersion := Some(\"$CIRCLE_BUILD_NUM\");publish"
      - save_cache:
          key: ivy
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: release
